### ISSUE TITLE
Update comparison between Memgraph and Neo4j

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#100]
Update the comparison between memgraph and neo4j in the cypher manual (https://memgraph.com/docs/querying/differences-in-cypher-implementations)

@gvolfing will help with a list, the rest compare docs

**Comment by kgolubic** [comment]
@gvolfing can you provide the list for me? Thanks!

**Comment by katarinasupe** [comment]
@gvolfing @kgolubic was something additional provided here? @gvolfing can you provide more information after the release so we can document it better for users migrating?

**Comment by gvolfing** [comment]
Yes, I will get on that soon.

**Comment by katarinasupe** [comment]
@gvolfing can you give me an ETA on that info being provided? I would love to get that out as soon as possible?

**Comment by katarinasupe** [comment]
There are other things of higher priority, so putting this issue on hold for now.
