### ISSUE TITLE
Feedback for “Install Memgraph on Ubuntu”

### ISSUE THREAD

**Issue by datapoesy** [memgraph/documentation#1075]
Memgraph cannot be installed on Ubuntu.  Looks like the product is not reliable since there is absolutely no documentation available to install this on Ubuntu.

**Comment by katarinasupe** [comment]
Hi @datapoesy, is this [documentation](https://memgraph.com/docs/getting-started/install-memgraph/ubuntu) not working for you? Can you please tell me what exactly is not working? 

Here is the download hub to download Memgraph for Ubuntu: https://memgraph.com/download

**Comment by datapoesy** [comment]
Hi, I got it running  on a vm with higher system configuration.  My initial attempts were on a 2 Core 4GB machine.  It would be great to mention system requirements in the documentation.  
It works for me now.  Very much appreciate your quick response; very much reassuring.  I am closing this ticket
Thanks again.

**Comment by katarinasupe** [comment]
Hi @datapoesy, thank you for the feedback, we will definitely work on improving that. Until then, I hope our [FAQ](https://memgraph.com/docs/help-center/faq#what-are-the-minimum-and-recommended-requirements-to-run-a-on-premise-instance) can help. 

If you have more questions, you can [join our Discord server](https://discord.gg/memgraph) of [book an office hours call](https://memgraph.com/office-hours).
