### ISSUE TITLE
Menu item disappears 

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#164]
When i'm on xml module i can see it in the left-side toc

![image](https://github.com/memgraph/documentation/assets/95473291/ab0c4de1-efe8-48cc-8cf3-d81e9fc97050)

but if i move to any other QM it disappears 

![image](https://github.com/memgraph/documentation/assets/95473291/8d0d16d7-9be3-4245-b823-3cd89c7eb787)

**Comment by kgolubic** [comment]
@vpavicic as far as I can see this is no longer the issue, at least not in deployed version:

I went to https://memgraph.com/docs/advanced-algorithms/available-algorithms/union_find, and I can see https://memgraph.com/docs/advanced-algorithms/available-algorithms/xml_module in a menu.
