### ISSUE TITLE
Fix order of menu items in FAQ/Errors

### ISSUE THREAD

**Issue by kgolubic** [memgraph/documentation#169]
The overview should be the top item, and it should be opened when the submenu is opened.

![image](https://github.com/memgraph/documentation/assets/46486712/0bc1880b-dd9a-439e-b72f-b7ee51dd5cb0)

**Comment by vpavicic** [comment]
Overview pages no longer work like this...
When you want an overview page section, the page is added to a folder lvl up, and it's automatically assigned as the overview page
