### ISSUE TITLE
Configuration page suggestions

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#207]
I would highlight enterprise features better and restructure the files. 

- In [security](https://memgraph.com/docs/configuration/monitoring-server), we have [User roles ](https://memgraph.com/docs/configuration/security#user-roles-enterprise-feature)+ [Privileges](https://memgraph.com/docs/configuration/security#privileges-enterprise-feature) and they form Role-based access control actually. 
- Monitoring server can be one page - [monitoring via WebSocket](https://memgraph.com/docs/configuration/monitoring-server) and monitoring via [HTTP server](https://memgraph.com/docs/configuration/exposing-system-metrics) (enterprise).
- [LDAP security](https://memgraph.com/docs/configuration/ldap-security) could be a part of [Auth module page](https://memgraph.com/docs/configuration/auth-module)

**Comment by vpavicic** [comment]
Did first 2 points

**Comment by vpavicic** [comment]
resolved with PR #208
