### ISSUE TITLE
Additional updates to Docker docs

### ISSUE THREAD

**Issue by kgolubic** [memgraph/documentation#228]
Note: branching from https://github.com/memgraph/documentation/issues/204

"Also, to know about env vars and how to set them up properly and which one they can configure in runtime. Another thing they are confused about is persistency and what happens with data in docker container.

Another thing inexperienced docker, but experienced database users might get confused by is the --name flag in docker. Sometimes they think it's a database name instead of a container name.

This docker guide should also include talk about permissions, that is already somewhere in our docs, and can include [init-flags docs](https://memgraph.com/docs/configuration/configuration-settings#use-init-flags-with-docker) that @vpavicic put in config currently."

Also we need to explaint the difference between `docker run` and `docker start`.

**Comment by vpavicic** [comment]
I wouldn't list the env variables and runtime setting on this page as we then have 2 places we need to update when this changes (and env variables will change soon AFAIK)

So i would mention it (i think we already do somewhere but we can go into more details about the principles of how they work) but i wouldn't list any rapidly changing info

I also think the init guide should stay in the configuration-settings page, but we can mention it and link to it

**Comment by kgolubic** [comment]
One more thing that we could/should add is the difference between `docker run `and `docker start`. I'll add it to the  list.

**Comment by kgolubic** [comment]
I've added the new section. Since there will be some changes related to init I will not address them at this time.
