### ISSUE TITLE
Uniqness constraint

### ISSUE THREAD

**Issue by antejavor** [memgraph/documentation#248]
Add missing context information about the implication of uniqueness constraints and indexes. 

Neo4j currently creates and index on uniqueness constraints, we do not, we should make it clear since users assume that it is there.

**Comment by vpavicic** [comment]
That information is present in the documentation, but I can bold the words "do not" or putt it in a callout section?

![image](https://github.com/memgraph/documentation/assets/95473291/1772df89-1556-4a4e-accb-0e5cc2f69ecc)
