### ISSUE TITLE
Feedback for “Read and modify data”

### ISSUE THREAD

**Issue by nishantPawzeeble** [memgraph/documentation#364]
https://memgraph.com/docs/querying/read-and-modify-data#reversing-traversals
On the above URL, I guess the query is incorrect for given scenario.
Please check and rectify.
Thank you.

Regards,
Nishant

**Comment by kgolubic** [comment]
@nishantPawzeeble thank you for reporting this. Yes, it was an incorrect query. This is now fixed.

**Comment by nishantPawzeeble** [comment]
Thank you. :)

Regards,
Nishant
