### ISSUE TITLE
Update the docs to describe which values are treated as t/f in toBoolean

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#377]
We have a scalar function [toBoolean](https://memgraph.com/docs/querying/functions#scalar-functions) in Memgraph. That function converts the argument to a boolean. Argument can be boolean, value or string. From the docs, it is not clear which values for those arguments are accepted. 

This is feedback from the community member: https://github.com/memgraph/memgraph/issues/1538

**Comment by kgolubic** [comment]
This was merged, then reversed and then merged again as part of https://github.com/memgraph/documentation/pull/411. Closing.

![image](https://github.com/memgraph/documentation/assets/46486712/af152546-64c8-4efa-8258-d6a4c37d860b)
