### ISSUE TITLE
Link pointing to a wrong page/section

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#447]
[Import data from CSV files](https://memgraph.com/docs/data-migration/csv) links to 
[copy the files from your local directory into Docker](https://memgraph.com/docs/getting-started/install-memgraph/docker#copy-files-from-and-to-a-docker-container) and that leads to docker page, without such section. There are 4 other pages with such links, 10 links across whole docs that are not leading to a proper section.

1. where is that section?
2. if there is no such section, where should that link?

This is reported from the community

**Comment by katarinasupe** [comment]
It should link here: https://memgraph.com/docs/getting-started/first-steps-with-docker#copy-files-from-and-to-a-docker-container

**Comment by kgolubic** [comment]
I've identified seven occurrences of this broken link. They are all fixed now.
