### ISSUE TITLE
Migrate module is not mentioned under Data migration

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#451]
I noticed we are not mentioning [the migrate module](https://memgraph.com/docs/advanced-algorithms/available-algorithms/migrate) under [Data migration](https://memgraph.com/docs/data-migration). It might be useful for some users to see alternative ways to migrate from MySQL, SQL Server and Oracle DB.

**Comment by kgolubic** [comment]
@katarinasupe we do mention it, but I'll move it to a new section.

![image](https://github.com/memgraph/documentation/assets/46486712/0c897310-655d-4b99-8ee1-21fb83d953bd)

**Comment by katarinasupe** [comment]
@kgolubic I didn't see that the migration module was mentioned below. I think there was no need for your fixes and that it was better before.
