### ISSUE TITLE
Wrong link linked

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#461]
In the [Check the location of the CSV files](https://memgraph.com/docs/data-migration/csv#import-files-with-and-no-header) section there's a wrong link to copying the files into the Docker container. It should be https://memgraph.com/docs/getting-started/first-steps-with-docker#copy-files-from-and-to-a-docker-container
instead of https://memgraph.com/docs/getting-started/install-memgraph/docker#copy-files-from-and-to-a-docker-container

**Comment by kgolubic** [comment]
Fixed.
