### ISSUE TITLE
Provide steps for a workaround when deleting larger scale data

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#481]
Users have had bad experiences when using `DETACH DELETE` on larger scale data. We should provide steps for a workaround in the [section of the docs](https://memgraph.com/docs/querying/clauses/delete#2-deleting-a-node-and-its-relationships) that explains `DELETE` clause and mentions `DETACH DELETE `.

[Context](https://memgraph.slack.com/archives/CS2LVJF5G/p1707845290613189) from a Slack conversation

**Comment by katarinasupe** [comment]
This should be added after it's implemented -> https://github.com/memgraph/mage/pull/446
