### ISSUE TITLE
Explain how storage flags values impact the db

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#497]
- snapshot flags on scale
- when to create snapshot (problems with in memory analytical)

**Comment by antejavor** [comment]
- when to create snapshot (problems with in memory analytical) -> in memory analytical section on storage modes page

This seems to be documented: 
https://memgraph.com/docs/fundamentals/storage-memory-usage#in-memory-analytical-storage-mode

**Comment by katarinasupe** [comment]
You're right 😄
