### ISSUE TITLE
 Inspect the logs without the excessive lab messages

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#498]
```
grep -v -E "SHOW STORAGE INFO|MATCH \(APP_INTERNAL_EXEC_VAR\) return COUNT\(APP_INTERNAL_EXEC_VAR\) as cnt|SHOW INDEX INFO|SHOW CONSTRAINT INFO|SHOW TRIGGERS" my_log_file.log
```

**Comment by katarinasupe** [comment]
Toni:
You can just search for `APP_INTERNAL_EXEC_VAR` because there are other Lab queries (e.g. when generating graph schema) that will have this for internal stuff
```
grep -v -E "SHOW STORAGE INFO|APP_INTERNAL_EXEC_VAR|SHOW INDEX INFO|SHOW CONSTRAINT INFO|SHOW TRIGGERS" my_log_file.log
```

**Comment by katarinasupe** [comment]
Sure. My suggestion: I would add a section under [List the content of the log](https://memgraph.com/docs/configuration/logs#list-the-content-of-the-log), after the current content -> List only Memgraph logs (explain why there are any other logs and which ones, and how to do it).

**Comment by kgolubic** [comment]
I've added a new section and crated a PR -> https://github.com/memgraph/documentation/pull/567
