### ISSUE TITLE
Give more details on how to set vm.max_map_count

### ISSUE THREAD

**Issue by gitbuda** [memgraph/documentation#529]
especially for the larger amounts of system memory

e.g. https://docs.actian.com/vector/5.0/User/Increase_max_map_count_Kernel_Parameter_(Linux).htm says
"where map_count should be around 1 per 128 KB of system memory"
For memgraph that number is probably different, but we should come with a table like:
* 128GB -> value
* 256GB -> value
* ...
* 2TB -> value
* 4TB -> value
* ...

**Comment by gitbuda** [comment]
@antoniofilipovic what are the recommended values for Memgraph depending on the available RAM under the system?

**Comment by antoniofilipovic** [comment]
I would recommend following also this link: https://docs.actian.com/vector/5.0/index.html#page/User/Increase_max_map_count_Kernel_Parameter_(Linux).htm link

Here are suggestions @kgolubic:
- From 8GB till 32GB RAM:
    ```
    echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
    ```
- For 64GB RAM:
    ```
    echo "vm.max_map_count=524288" | sudo tee -a /etc/sysctl.conf
    ```
- For 128GB RAM:
    ```
    echo "vm.max_map_count=1048576" | sudo tee -a /etc/sysctl.conf
    ```
- For 256GB RAM:
    ```
    echo "vm.max_map_count=2097152" | sudo tee -a /etc/sysctl.conf
    ```
- For 512GB RAM:
    ```
    echo "vm.max_map_count=4194304" | sudo tee -a /etc/sysctl.conf
    ```
- For 1TB RAM:
    ```
    echo "vm.max_map_count=8388608" | sudo tee -a /etc/sysctl.conf
    ```
- For 1.5TB RAM:
    ```
    echo "vm.max_map_count=12582912" | sudo tee -a /etc/sysctl.conf
- For 2TB RAM:
    ```
    echo "vm.max_map_count=16777216" | sudo tee -a /etc/sysctl.conf
    ```
- For 2.5TB RAM:
    ```
    echo "vm.max_map_count=20971520" | sudo tee -a /etc/sysctl.conf

Important note: 
    ```
- For 3TB RAM:
    ```
    echo "vm.max_map_count=25165824" | sudo tee -a /etc/sysctl.conf
    ```
- For 3.5TB RAM:
    ```
    echo "vm.max_map_count=29360128" | sudo tee -a /etc/sysctl.conf
    ```
- For 4TB RAM:
    ```
    echo "vm.max_map_count=33554432" | sudo tee -a /etc/sysctl.conf
    ```



Afterward, you need to run: `sudo sysctl -p`

**Comment by kgolubic** [comment]
We already have the info similar to the one that you referred to (https://docs.actian.com/vector/5.0/User/Increase_max_map_count_Kernel_Parameter_(Linux).htm ). Our docs are located at https://memgraph.com/docs/configuration/system-configuration#increasing-memory-map-areas an this is the place where I'll add this table.

![image](https://github.com/memgraph/documentation/assets/46486712/3ca7002b-ead8-4c62-8b1b-3e51732aef75)
