### ISSUE TITLE
Release notes 2.15 - 2 issues, some tips

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#550]
Sorry, I don't understand these notes

![image](https://github.com/memgraph/documentation/assets/95473291/12d98641-c7ea-4aab-8436-c95478b63412)
![image](https://github.com/memgraph/documentation/assets/95473291/de430506-df61-4a06-af87-cab2dccef166)

I also feel like the release note could have been that HA has been introduced (1 note) because all of this additional information is not really important to write as separate information/release notes (you don't have to change this, but just a thought for future releases). They are all a part of this new feature that people never saw before so the documentation page should have included all this information (if they are relevant to the user) and the release note would just be 1 with the link to the docs page.

[question not relevant to the release notes - why are there now 2 replication pages and a HA page? Feels like all three of these pages are on the same topic?]

When you link release notes with the rest of the documentation, you can only choose one word from the release note and just add a link to that word. That way you don't have to write additional sentences such as "For more information... " or "Refere to SOMETHING"

Also there are 3 different ways how GitHub links are written so maybe only one should be used:
/(with a dash) - #1234
#1234
1234

**Comment by kgolubic** [comment]
I will fix the two bullet points that you have mentioned, as well as the way that PRs are linked. I will go with `#1234`.

I would leave the full sentences when linking the docs. I'd like to give the information that the link goes to the documentation page.
