### ISSUE TITLE
HA page feedback

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#560]
1. Check the spelling with Grammarly + check if all is well written in code blocks, e.g., code block typo - "Memgraph 2.15 introduced high availability enterprise feature which is only enabled if used with `--experimental-enabled=high-availability` flag."
2. Is it `--restore-replication-state-at-startup`, `--replication-state-at-startup=true`, `--replication-restore-state-on-startup`? In config `--replication-restore-state-on-startup` without default value with description set to true -- unclear what is correct and what needs to be used?
3. I would remove "We plan to add support for ASYNC replicas in 2.16." - In my opinion, these kind of sentences are not necessary in the docs that refer to the current version of Memgraph. Also, this puts additional work after following releases. In general, it is good to avoid using 'we' in technical documentation.
4. Empty section between Cluster management and Setting config for highly-available cluster
5. I would avoid saying "Memgraph's 2.15 release added several flags for managing the cluster." in text. In my opinion, it would be better to add all newly introduced flags to the warning admonition in the beginning.
6. Failover procedure section should be rewritten. First section is quite unclear and has code formatting issues. Other sections are missing commas here and there, making it hard to understand. Some sentences are missing additional explanation, such as "REPLICA always returns as REPLICA" (returns what, from where, to where)
7. Are RPC request and RAFT protocol basic terms in replication? If not, we should maybe add one sentence explaining them.
8. Saying alive REPLICA sounds weird. Is that correct?
9. This is unclear to me - "Once each alive REPLICA acknowledges that it stopped listening to the old MAIN, the coordinator sends a RPC request to the potential new MAIN, which is still in REPLICA state, to promote itself to MAIN instance and sends all instances from the cluster to which the new MAIN will replicate data. If the instance is down at the moment, the new MAIN will establish a connection at a later point when it comes back up, and recover it to the correct state."
10. Is it REPLICAs or replicas? If it's replicas, why it's not mains, but MAINs.
11. This is unclear to me - "When MAIN is demoted to REPLICA it can happen that MAIN gets demoted, but setting now new REPLICA to listen to the current MAIN fails.""
12. This is unclear to me - "If at some point it happens that MAIN goes down, but REPLICA, which is chosen as the new MAIN, has less up-to-date data than other REPLICAs, failover won't succeed as from MAINs perspective it cannot become new MAIN as it has some other instance which is more up to date and therefore diverged from the new MAIN."
13. I would again avoid saying: "In the Memgraph 2.15 release..."

**Comment by kgolubic** [comment]
1. Fixed
2. I will create a separate issue for this.
3. Fixed
4. Fixed
5. I wouldn't move it to the top of the admonition. I've rephrased the start of that section.
6. I will create a separate issue for this.
7. They are pretty standard, but I've added two admonitions 
8. We could replace `alive REPLICA` with `operational REPLICA instance` or just `operational REPLICA` but we use in the output of the `SHOW INSTANCES` command the term `alive` so I would stick with it.
9. I will create a separate issue for this.
10. All updated except one that could be mistaken for a command (SYNC REPLICAs).
11. I will create a separate issue for this.
12. I will create a separate issue for this.
13. Fixed

**Comment by kgolubic** [comment]
Points marked as fixed will be resolved in https://github.com/memgraph/documentation/pull/561.
For other points new issue was created - https://github.com/memgraph/documentation/issues/562

**Comment by katarinasupe** [comment]
> 8. We could replace alive REPLICA with operational REPLICA instance or just operational REPLICA but we use in the output of the SHOW INSTANCES command the term alive so I would stick with it.

I was saying this because it is not correct to use alive before the noun. 

> Generally, live is an attributive adjective, and alive is used as a predicate adjective; in other words, live is usually placed directly before the noun, and alive is generally not. These are live goldfish. These goldfish are alive.
[Source](https://english.stackexchange.com/questions/87318/what-is-the-difference-between-the-adjectives-live-and-alive#:~:text=Generally%2C%20live%20is%20an%20attributive,These%20goldfish%20are%20alive)

I would use the term running REPLICA since we often use running Memgraph instances. There might be another term for this that is often used in the db world, so I suggest exploring this a bit before the final decision.
