### ISSUE TITLE
Fixed and updated need for HA page

### ISSUE THREAD

**Issue by kgolubic** [memgraph/documentation#562]
Based on the feedback from @katarinasupe in https://github.com/memgraph/documentation/issues/560 some updates to HA page are needed:

1. Is it `--restore-replication-state-at-startup`, `--replication-state-at-startup=true`, `--replication-restore-state-on-startup`? In config `--replication-restore-state-on-startup` without default value with description set to true -- unclear what is correct and what needs to be used?
2. Failover procedure section should be rewritten. First section is quite unclear and has code formatting issues. Other sections are missing commas here and there, making it hard to understand. Some sentences are missing additional explanation, such as "REPLICA always returns as REPLICA" (returns what, from where, to where)
3. This is unclear to me - "Once each alive REPLICA acknowledges that it stopped listening to the old MAIN, the coordinator sends a RPC request to the potential new MAIN, which is still in REPLICA state, to promote itself to MAIN instance and sends all instances from the cluster to which the new MAIN will replicate data. If the instance is down at the moment, the new MAIN will establish a connection at a later point when it comes back up, and recover it to the correct state."
4. This is unclear to me - "When MAIN is demoted to REPLICA it can happen that MAIN gets demoted, but setting now new REPLICA to listen to the current MAIN fails.""
5. This is unclear to me - "If at some point it happens that MAIN goes down, but REPLICA, which is chosen as the new MAIN, has less up-to-date data than other REPLICAs, failover won't succeed as from MAINs perspective it cannot become new MAIN as it has some other instance which is more up to date and therefore diverged from the new MAIN."

**Comment by antoniofilipovic** [comment]
@kgolubic please check if everything is fine: https://github.com/memgraph/documentation/pull/628
1. Fixed
2. @kgolubic you fixed that part, right?
3. Fixed
4. Fixed
5. Fixed
