### ISSUE TITLE
Functions page issues

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#565]
Under the [User-defined functions](https://memgraph.com/docs/querying/functions#user-defined-functions) section of the docs, there's a link to the query modules leading to Advanced algorithms instead of query modules.

**Comment by katarinasupe** [comment]
On the same page, admonition about aggregation functions + DISTINCT should be under [Aggregation functions](https://memgraph.com/docs/querying/functions#aggregation-functions), not under Graph projection functions.
