### ISSUE TITLE
Explain timeout on Errors page

### ISSUE THREAD

**Issue by antejavor** [memgraph/documentation#590]
Transaction was asked to abort because of transaction timeout. 

Page: https://memgraph.com/docs/help-center/errors 

Context: https://discord.com/channels/842007348272169002/890968976627228752/1217756712266891305

**Comment by katarinasupe** [comment]
I now realized that all transaction errors should be under one Transaction page. Hence, I would update Conflicting transactions page and put both transaction timeout and conflicting transactions there. Wdyt?
