### ISSUE TITLE
Provide best practice about what is the most efficient way to import data in `mgconsole`

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/documentation#625]
Provide best practices about what is the most efficient way to import data through `mgconsole`

**Comment by katarinasupe** [comment]
What kind of data? This is what we have for now -> https://github.com/memgraph/best-practices/tree/main/import/cypher#how-to-import-cypherl-into-memgraph

**Comment by kgolubic** [comment]
@Josipmrden is info that @katarinasupe has provided enough, or are we missing something from the docs?
