### ISSUE TITLE
Document the regex better in Memgraph

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/documentation#641]
we have 2 related flags --auth-user-or-role-name-regex= and --auth-password-strength-regex=
The regular expression syntax is based on the modified ECMAScript regular expression grammar. The ECMAScript grammar can be found [here](http://ecma-international.org/ecma-262/5.1/#sec-15.10), while the modifications are described in [this document](https://en.cppreference.com/w/cpp/regex/ecmascript). (if this is applied in all cases, just a quick verification needed), the same (or very similar sentence) should be located near

also, wherever regex is mentioned, we can either link to  https://memgraph.com/docs/querying/clauses/where#3-regular-expressions

or some other dedicated place in Memgraph

**Comment by kgolubic** [comment]
We have three different regex-related situations:

1. For regex in WHERE clause, we use Modified ECMAScript regular expression grammar (https://en.cppreference.com/w/cpp/regex/ecmascript)
2. For text (https://memgraph.com/docs/advanced-algorithms/available-algorithms/text#regexgroups) we use C++ regex https://en.cppreference.com/w/cpp/regex
3. And for text search (https://memgraph.com/docs/configuration/text-search#regex-search), we use https://github.com/quickwit-oss/tantivy
