### ISSUE TITLE
Document the configuration of the docker-compose file better

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#670]
- explain the `command` line and it's syntax → flags should be added (with “” and comma inbetween)
- mention examples of having more config flags
- how to change config after deploying the database → docker restart vs docker down/up

**Comment by antejavor** [comment]
Please add the Docker compose card: https://github.com/memgraph/documentation/pull/691#discussion_r1567171159

**Comment by antejavor** [comment]
Pelase add the Docker compose for env: https://github.com/memgraph/documentation/pull/691/files#diff-3d9eed09cb1145f8eca058ea41ee667ced86663f6d04c5a291f19f278cbc7474R367
