### ISSUE TITLE
Update the info about the schema.assert procedure

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#673]
On the querying docs under the [schema assert](https://memgraph.com/docs/querying/schema#delete-all-indexes-and-constraints) section, there's an info on dropping all indexes and constraints that should be deleted since there are now edge-type indexes that are not affected by that. [Context](https://memgraph.slack.com/archives/C066Q419WDC/p1712663124703279?thread_ts=1712579506.840509&cid=C066Q419WDC)

**Comment by katarinasupe** [comment]
@kgolubic is this fixed?

**Comment by kgolubic** [comment]
> @kgolubic is this fixed?

No, not yet. Will bump it up on the list of prioreties.
