### ISSUE TITLE
Remove pattern comprehension in Cypher differences

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#682]
When opening the issue to keep Cypher differences updated, I was mainly referring to the fact that pattern comprehension is now supported in Memgraph and it can be removed from this page -> Pattern comprehension section under https://memgraph.com/docs/querying/differences-in-cypher-implementations#unsupported-constructs

**Comment by kgolubic** [comment]
Will be closed by https://github.com/memgraph/documentation/pull/686
