### ISSUE TITLE
Remove clause from 'DROP GRAPH clause'

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#683]
All clauses under Clauses section don't have 'clause' after their name. Only DROP GRAPH has it. Remove it.

**Comment by katarinasupe** [comment]
Also, clauses are put in alphabetical order, so keep the order as it should be

**Comment by katarinasupe** [comment]
Also, as I commented on PR, should DROP GRAPH even be under Clauses?

**Comment by kgolubic** [comment]
I think that at the moment, Clauses is the best place to `DORP GRAPH` docs. I'll fix the other reported issues, but I'll leave the page where it is located at this point.
