### ISSUE TITLE
Replica - Physical Resources Clarity

### ISSUE THREAD

**Issue by Ana-Marija-design** [memgraph/documentation#726]
Current documentation page for [Replication](https://memgraph.com/docs/configuration/replication) isn't clear enough about the fact that **Replicas require the same physical resources as main instances.**

@kgolubic feel free to add any potential questions to the issue thread and I'll go on a journey of discovery to find answers for you. (I'll ask Buda:) 
Please check and add questions before Tuesday (I got Buda on speed-dial on Tuesdays)

**Comment by kgolubic** [comment]
1. What does "same physical resources as main instances" mean? 
2. Do they need to have the same CPU architecture (x86/AARCH)?
3. Can one instance be Docker based, another native on on-prem, and another one in the cloud?

**Comment by Ana-Marija-design** [comment]
Same physical resources as main refers to CPU and memory. This is most important/necessary to get across, some assumptions created mismatched expectation w/Orbis because they had an idea to "save" on replicas.

As to no 2. and 3., in theory it _could_ work, but does depend on the compatibility of architectures so should be tested and we don't actually recommend/guarantee.

**Comment by kgolubic** [comment]
@Ana-Marija-design and @gitbuda I need more clarification for "Same physical resources as main refers to CPU and memory.". Does this mean that machines must use two identical CPUs and the same amount of RAM? By identical CPU, I mean the same manufacturer and model.

**Comment by Ana-Marija-design** [comment]
The same amount of RAM = hard yes. 
CPUs = Not such a hard yes. Quite possibly different ones could/would work, but we don't really check this and can't guarantee it. 

At the very least, each replica can become a main and will need the same resources to run smoothly. @gitbuda correct me if I've not stated the CPU issue well.
