### ISSUE TITLE
Feedback for “Release notes”

### ISSUE THREAD

**Issue by vishnun** [memgraph/documentation#756]
The section about MAGE v1.14.0 mentions that Link Prediction and Node Classification with GNN is no longer available.
https://memgraph.com/docs/release-notes#unavailable-algorithms-in-mage-v1140-and-newer-versions

However, it does not mention WHY it's no longer supported. Also, it does not guide on how I could achieve that going forward in Memgraph?

**Comment by katarinasupe** [comment]
Hi @vishnun and thank you for opening the issue. We have opened issues for the modules that are missing:
- https://github.com/memgraph/mage/issues/470
- https://github.com/memgraph/mage/issues/469 
- https://github.com/memgraph/mage/issues/448

On those issues, you can keep track of the progress of including them in MAGE. I will try to find out more from the team and get back to you as soon as I have update. 

Are those modules a blocker for your project with Memgraph?

**Comment by vishnun** [comment]
Thanks Katarina. 
I don't see any updates on those issues but will keep an eye on those. 

And yes, we need those algorithms to be about to achieve our goals. And if we have to build those from scratch, it'll be a lot more effort and will take much longer as it's not my area of expertise.


Hence, it's a blocker to consider Memgraph for my project.

**Comment by katarinasupe** [comment]
Hi @vishnun, the issues will be updated at the beginning of next week since new prioritization tags will be added over the weekend.

**Comment by kgolubic** [comment]
@vishnun thnank you for reporting this. I've updated the release notes with the additional information.
