### ISSUE TITLE
Add subgraph as an optional argument to MAGE procedures

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#757]
Reported from the community:

> Yeah the docs do not even show get() even ACCEPTING a graph (at https://memgraph.com/docs/advanced-algorithms/available-algorithms/pagerank) and I didn't think to check the run-alogrithms page - thanks for that link! @Katarina | Memgraph  is it possible to update the pagerank docs so others can know that it accepts a graph? Or even show those examples there in the pagerank docs from the run-algos page?

[Source](https://discord.com/channels/842007348272169002/890968055339958292/1238900081403367514) 

My comment: We did add a note that all modules can be run on a subgraph, but not having a subgraph listed as an optional argument in the get() procedure is incorrect.

**Comment by kgolubic** [comment]
@katarinasupe, does this mean that we should add a subgraph as an optional argument in the get() procedure to all algorithms?
