### ISSUE TITLE
Granting privileges query not working

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#781]
I noticed GRANT ALL PRIVILEGES FROM does not work, but GRANT ALL PRIVILEGES TO works. Please check before fixing this at https://memgraph.com/docs/database-management/authentication-and-authorization/role-based-access-control#manage-all-privileges-at-once

**Comment by kgolubic** [comment]
I've checked our [Grammar](https://github.com/memgraph/memgraph/blob/d6e9ebfe5bd044b3a352fd33609384a37dc67f00/src/query/frontend/opencypher/grammar/MemgraphCypher.g4#L340). Here is what I've found:

```
grantPrivilege : GRANT ( ALL PRIVILEGES | privileges=grantPrivilegesList ) TO userOrRole=userOrRoleName ;
denyPrivilege : DENY ( ALL PRIVILEGES | privileges=privilegesList ) TO userOrRole=userOrRoleName ;
revokePrivilege : REVOKE ( ALL PRIVILEGES | privileges=revokePrivilegesList ) FROM userOrRole=userOrRoleName ;
```

I'll update the docs accordingly.
