### ISSUE TITLE
SHOW USERS is not documented

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#886]
there's missing info about the `SHOW USERS` query under the [Users](https://memgraph.com/docs/database-management/authentication-and-authorization/users) section of the docs

**Comment by tiffany76** [comment]
Hi! I'm a first-time contributor. This seemed like a good first issue, so I just put up a PR. 

I read your contributing guidelines. I wasn't able to add the `status: ready` label for the PR, but it's ready for review. 

Thanks!

**Comment by kgolubic** [comment]
Hi @tiffany76! Thank you for the PR. I've added the label to the [PR](https://github.com/memgraph/documentation/pull/952).
