### ISSUE TITLE
Unfinished sentence in the Install Memgraph section

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#912]
In the [Install Memgraph](https://memgraph.com/docs/getting-started/install-memgraph) section of the docs, the first paragraph is unfinished:

> If you're new to Memgraph we recommend running [Memgraph Platform](https://memgraph.com/docs/getting-started#install-memgraph-platform), a multi-container application. It includes the database

**Comment by katarinasupe** [comment]
I think there is just a weird line break + empty row
