### ISSUE TITLE
Update ports used in HA docs

### ISSUE THREAD

**Issue by kgolubic** [memgraph/documentation#922]
From internal Slack channel:

> One port to rule them all, but should be consistent in docs.
> 
> There are configuration flags on page for High availability, but when we describing Env flags
> the config is not the same as it is used in docker parameters in previous paragraph,
> and that is confusing
> 
> Data and Coordinator instances paragraphs
> 
> `export MEMGRAPH_BOLT_PORT=7692`
> 
> There is 7692 port specified, but should be 7687 (to be consistent on this page.
> https://memgraph.com/docs/clustering/high-availability

**Comment by katarinasupe** [comment]
@as51340, next time you update HA docs, can you take a look at this and make sure all ports used on the page are correct? I don't want to get into this rabbit hole now, and I think it will be easier if you update it on the fly.
