### ISSUE TITLE
memgraph questions on bookmark

### ISSUE THREAD

**Issue by ramesh0279** [memgraph/documentation#926]
Neo4j provides us a way to ensure strong consistency using bookmarks. Bookmarks are supported in the neo4j java driver client.
Is this supported in memgraph?

**Comment by katarinasupe** [comment]
Closing this issue since it's responded above. For more questions, @ramesh0279, please [join our Discord server](https://discord.gg/memgraph) or [book an office hours call](https://memgraph.com/office-hours).
