### ISSUE TITLE
Missing Enterprise features

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#961]
Some issues on the Memgraph Enterprise page - https://memgraph.com/docs/database-management/enabling-memgraph-enterprise

OIDC integration is mentioned twice
There is no SSO, automatic failover nor collaboration option in the Lab

**Comment by hal-eisen-MG** [comment]
And @Josipmrden just told me that TTL is missing also

**Comment by hal-eisen-MG** [comment]
Automatic failover is part of `High availability` - do you think it needs an extra mention in the top list?

**Comment by hal-eisen-MG** [comment]
While SSO is already present under Auth System Integrations - do these aliases need to be explicit?
