### ISSUE TITLE
Clarify docs on Role based access control

### ISSUE THREAD

**Issue by antejavor** [memgraph/documentation#986]
It looks like you need these permissions to create some node or relationship: 

CREATE DATABASE db;
GRANT ALL PRIVILEGES TO `user`;
GRANT DATABASE * TO `user`;
GRANT CREATE_DELETE ON LABELS * TO `user`;
GRANT CREATE_DELETE ON EDGE_TYPES * TO `user`;
SHOW USERS;

It is not sufficient to do  `GRANT ALL PRIVILEGES TO `user`;` `GRANT DATABASE * TO `user`;` 

We should revisit: https://memgraph.com/docs/database-management/authentication-and-authorization/role-based-access-control

Context: https://discord.com/channels/842007348272169002/1278498722270937158/1283321686376190054

**Comment by hal-eisen-MG** [comment]
Some new documentation was added in https://memgraph.com/docs/database-management/multi-tenancy
