### ISSUE TITLE
Document meaning of notes upon Memgraph binary installation

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#99]
When a user installs the Memgraph binary, they get a note about missing Python packages. It can be unclear to the user what this means and what to do next. We should document it better.
Here is the report: https://discord.com/channels/842007348272169002/842008652377751582/1124012471733190767
Here is the discussion to add to docs: https://memgraph.slack.com/archives/CSR01RS80/p1688056540942609

**Comment by kgolubic** [comment]
Due to the [issues with WSL](https://github.com/memgraph/memgraph/issues/1551) I can't test this at the moment.

**Comment by kgolubic** [comment]
I couldn't reproduce this on Ubuntu and Fedora running under WSL. Closing.
